trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: 'dev-var'
   
steps:
  - script: |
      echo "My application is $(appname)"
      echo "My environment is $(environment)"
    