trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

job:
  job: dev
  displayName: 'Development Job'

  variables:
    - group: 'dev-var'
   
  steps:
    - script: |
        echo "My application is $(appname)"
        echo "My environment is $(environment)"

  job: prod
  displayName: 'Production Job'

  variables:
    - group: 'prod-var'

  steps:
    - script: |
        echo "My application is $(appname)"
        echo "My environment is $(environment)"
